image: google/dart:2.1

before_script:
  - export PATH="$PATH":"$HOME/.pub-cache/bin"
  - pub version
  - pub upgrade

pages:
  stage: deploy
  script:
  - pub global activate webdev
  - pub get
  - webdev build --output web:build
  - mv build public
  artifacts:
    paths:
    - public
  only:
  - master
