apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi
  labels:
    app: restapi
spec:
  selector:
    matchLabels:
      app: restapi
  template:
    metadata:
      labels:
        app: restapi
    spec:
      imagePullSecrets:
        - name: gitlab-registry-credentials
      containers:
        - name: restapi
          image: {{ CI_REGISTRY_IMAGE }}/restapi:latest
          resources:
            limits:
              cpu: 50m
              memory: 100M
          ports:
            - containerPort: 5000
          