apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ CI_COMMIT_REF_NAME }}-sqllite
spec:
  selector:
    matchLabels:
      app: {{ CI_COMMIT_REF_NAME }}-sqllite
  template:
    metadata:
      labels:
        app: {{ CI_COMMIT_REF_NAME }}-sqllite
    spec:
      imagePullSecrets:
      - name: gitlab-registry-credentials
      containers:
      - name: app
        image: {{ CI_REGISTRY_IMAGE }}/sqllite-{{ CI_COMMIT_REF_NAME }}:latest
        ports:
        - containerPort: 6379
        livenessProbe:
          httpGet:
            path: /index.html
            port: 6379
          periodSeconds: 60
          failureThreshold: 1

