apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ CI_COMMIT_REF_NAME }}-ing-cert
spec:
  secretName: {{ CI_COMMIT_REF_NAME }}-ing-cert-tls
  commonName: {{ HOST }}
  dnsNames:
    - {{ HOST }}
  duration: 30d
  renewBefore: 7d
  issuerRef:
    group: cas-issuer.jetstack.io
    kind: GoogleCASClusterIssuer
    name: googlecasclusterissuer-sample
