apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
spec:
  rules:
  - host: "master-{{ HOST }}"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: master-webapp-svc
            port:
              number: 80
  - host: "staging-{{ HOST }}"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: staging-webapp-svc
            port:
              number: 80  
  - host: "working-{{ HOST }}"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: working-webapp-svc
            port:
              number: 80
  tls:
  - secretName: webapp-ing-cert
    hosts: 
    - "master-{{ HOST }}"
    - "staging-{{ HOST }}"
    - "working-{{ HOST }}"
